import Head from "next/head";
import Link from "next/link";
import { SectionOne, ContainerSC, PodcastSection, Header, SectionTwo } from "./styles-index";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main>
        <Header></Header>
        <SectionOne>
          <ContainerSC>
            <h1>
              Podcasts <span>Sacocheio.tv</span>
            </h1>
            <PodcastSection>
              <Link href="/desinformacao">
                <button>Desinformação</button>
              </Link>
              <Link href="/sacocheio">
                <button>Saco Cheio</button>
              </Link>
              <Link href="/aderiva">
                <button>Á deriva</button>
              </Link>
            </PodcastSection>
          </ContainerSC>
        </SectionOne>

        <SectionTwo>
        
        </SectionTwo>
      </main>
    </>
  );
}
